### ISSUE TITLE
API Legacy ShutDown

### ISSUE THREAD

**Issue by LivC182** [hendrikbgr/Instagram-Selenium-Bot#11]
Hi Sorry to bother you, great code btw. I was wondering if your code will still work after march when the Legacy API shuts down. I don't see in your code any api_token, so I assume it will still work. But I am not sure, maybe you can shed some light

**Comment by hendrikbgr** [comment]
Yes, the script will still work after the update. This was the intention from the beginning the create a script which would not use any API. The script simulates user behaviour in a browser.

Thanks for opening an issue!
