### ISSUE TITLE
Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by Abdulsamipy** [hendrikbgr/Instagram-Selenium-Bot#14]
**Describe the bug**
Selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities 

**To Reproduce**
Steps to reproduce the behaviour:

1. Start '...'
2. See error '...'

**Expected behaviour**
detect the driver and start the browser 

**Screenshots**
![Capture](https://user-images.githubusercontent.com/58009877/76686174-67df1c00-663b-11ea-9a25-a385532b319d.PNG)

**Desktop (please complete the following information):**
 - OS: [e.g.Windows 10]
 - Version [e.g. 0.1.3]

**Additional context**

**Comment by hendrikbgr** [comment]
Could you please provide a screenshot of the full log? But might be worth checking thing out as well: https://stackoverflow.com/questions/53953524/selenium-unable-to-find-a-matching-set-of-capabilities-despite-driver-being-in I don't have a windows machine to test on

**Comment by hendrikbgr** [comment]
Also please make sure to always use the newest version of the bot. Please download 0.1.6 or the newest version available and try and replicate the error.

**Comment by hendrikbgr** [comment]
You need to update your Firefox version. If you don't have to normal firefox browser you need to install that. Also, keep firefox and the bot up to date.
